### ISSUE TITLE
A way to reload the cards?

### ISSUE THREAD

**Issue by alexgoodison** [D-32/DMSwipeCards#6]
Is there any way I could reload the SwipeCards such as you can reload a CollectionViewController?

**Comment by D-32** [comment]
No, but you could add some reset method which you would call before addCards. In that method you probably just have to do the following for it to work:
```
for cv in loadedCards {
  cv.removeFromSuperview()
}
loadedCards.removeAll()
```

**Comment by alexgoodison** [comment]
Perfect Thank you!

**Comment by alexgoodison** [comment]
What is cv and loadedCards? I can't seem to get it working.

**Comment by alexgoodison** [comment]
Really the one problem I'm having is locating `loadedCards` Are they in an array of some sort?

**Comment by D-32** [comment]
`cv` is a variable. You can use what ever you want, it's just some sample code I wrote for you. `loadedCards` is the array of cards. It's inside the class `DMSwipeCardsView` which is located inside `DMSwipeCardsView.swift`. They're literally only two classes in this library...

**Comment by alexgoodison** [comment]
Thank you, but I can't access `loadedCards` in my ViewController as it is a `fileprivate var` . How can I change this

**Comment by D-32** [comment]
You should be adding this new method to `DMSwipeCardsView.swift`. Of course you can also make the `var` public, and do it from the outside.

**Comment by alexgoodison** [comment]
Great! It works Thank you
